import { AfterViewInit, ElementRef, EventEmitter, TemplateRef, ViewContainerRef, OnInit } from '@angular/core';
import { SwipeServiceService } from '../swipe-service.service';
export declare class ItemListComponent implements AfterViewInit, OnInit {
    private swService;
    alive: boolean;
    result: boolean;
    selfElement: any;
    idElement: any;
    inside: {
        id: any;
        title: '';
        subTitle: '';
        mark: false;
    };
    disabledMark: boolean;
    showMark: boolean;
    itemClass: string;
    defaultEdit: TemplateRef<any>;
    defaultTrash: TemplateRef<any>;
    defaultMark: TemplateRef<any>;
    defaultNotMark: TemplateRef<any>;
    defaultCustom: TemplateRef<any>;
    customTemplate: TemplateRef<any>;
    editTemplate: TemplateRef<any>;
    trashTemplate: TemplateRef<any>;
    markTemplate: TemplateRef<any>;
    notMarkTemplate: TemplateRef<any>;
    callback: EventEmitter<any>;
    swClick: EventEmitter<any>;
    viewContainerEdit: ViewContainerRef;
    viewContainerTrash: ViewContainerRef;
    viewContainerMark: ViewContainerRef;
    viewContainerCustom: ViewContainerRef;
    clickOut(event: any): void;
    constructor(elRef: ElementRef, swService: SwipeServiceService);
    ngAfterViewInit(): void;
    private random;
    swipeleft: (res: any) => void;
    clickItem: (a: any) => void;
    action: (opt?: string) => void;
    ngOnInit(): void;
    render: () => void;
}
